//
//  GlukloaderYosemite.swift
//  Glukloader
//
//  Created by Alexandre Normand on 8/29/16.
//  Copyright (c) 2016 Glukit. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import Cocoa

public class GlukloaderYosemite : NSObject {

    //// Cache

    private struct Cache {
        static let color0: NSColor = NSColor(calibratedRed: 0.071, green: 0.071, blue: 0.071, alpha: 1)
        static var imageOfGlukitIcon: NSImage?
    }

    //// Colors

    public class var color0: NSColor { return Cache.color0 }

    //// Drawing Methods

    public class func drawGlukitIcon() {
        //// General Declarations
        let context = NSGraphicsContext.currentContext()!.CGContext

        //// GlukitDroplet
        NSGraphicsContext.saveGraphicsState()
        CGContextTranslateCTM(context, 2.68, 0)
        CGContextScaleCTM(context, 0.1, 0.1)



        //// Bezier 3 Drawing
        let bezier3Path = NSBezierPath()
        bezier3Path.moveToPoint(NSMakePoint(109.46, 51.38))
        bezier3Path.curveToPoint(NSMakePoint(109.35, 47.18), controlPoint1: NSMakePoint(109.48, 48.98), controlPoint2: NSMakePoint(109.5, 50.38))
        bezier3Path.curveToPoint(NSMakePoint(99.94, 20.4), controlPoint1: NSMakePoint(108.66, 37.61), controlPoint2: NSMakePoint(105.87, 28.14))
        bezier3Path.curveToPoint(NSMakePoint(75.4, 3.15), controlPoint1: NSMakePoint(93.69, 12.24), controlPoint2: NSMakePoint(84.91, 6.56))
        bezier3Path.curveToPoint(NSMakePoint(60.07, 0), controlPoint1: NSMakePoint(70.55, 1.41), controlPoint2: NSMakePoint(65.23, 0.07))
        bezier3Path.curveToPoint(NSMakePoint(14.54, 15.06), controlPoint1: NSMakePoint(39.72, 0), controlPoint2: NSMakePoint(26.58, 2.9))
        bezier3Path.curveToPoint(NSMakePoint(1.98, 35.81), controlPoint1: NSMakePoint(8.81, 20.83), controlPoint2: NSMakePoint(4.32, 27.94))
        bezier3Path.curveToPoint(NSMakePoint(0.02, 51.38), controlPoint1: NSMakePoint(0.45, 40.85), controlPoint2: NSMakePoint(-0.13, 46.12))
        bezier3Path.lineToPoint(NSMakePoint(109.46, 51.38))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4
        GlukloaderYosemite.color0.setFill()
        bezier3Path.fill()


        //// Bezier 6 Drawing
        let bezier6Path = NSBezierPath()
        bezier6Path.moveToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.curveToPoint(NSMakePoint(77.96, 145.84), controlPoint1: NSMakePoint(76.76, 156.31), controlPoint2: NSMakePoint(77.41, 150.77))
        bezier6Path.curveToPoint(NSMakePoint(81.76, 128.11), controlPoint1: NSMakePoint(78.67, 139.84), controlPoint2: NSMakePoint(80.13, 133.92))
        bezier6Path.curveToPoint(NSMakePoint(90.5, 102.3), controlPoint1: NSMakePoint(84.21, 119.36), controlPoint2: NSMakePoint(87.22, 110.77))
        bezier6Path.curveToPoint(NSMakePoint(95.51, 90.51), controlPoint1: NSMakePoint(92.03, 98.33), controlPoint2: NSMakePoint(93.59, 94.32))
        bezier6Path.curveToPoint(NSMakePoint(108.32, 62.17), controlPoint1: NSMakePoint(100.77, 81.55), controlPoint2: NSMakePoint(104.86, 71.97))
        bezier6Path.lineToPoint(NSMakePoint(108.3, 62.14))
        bezier6Path.lineToPoint(NSMakePoint(108.29, 62.16))
        bezier6Path.lineToPoint(NSMakePoint(108.25, 62.01))
        bezier6Path.curveToPoint(NSMakePoint(108.24, 61.96), controlPoint1: NSMakePoint(108.23, 61.98), controlPoint2: NSMakePoint(108.24, 62))
        bezier6Path.curveToPoint(NSMakePoint(108.04, 61.61), controlPoint1: NSMakePoint(108.11, 61.73), controlPoint2: NSMakePoint(108.18, 61.84))
        bezier6Path.curveToPoint(NSMakePoint(106.09, 60.21), controlPoint1: NSMakePoint(107.6, 60.97), controlPoint2: NSMakePoint(106.79, 60.5))
        bezier6Path.curveToPoint(NSMakePoint(99.47, 58.91), controlPoint1: NSMakePoint(103.98, 59.35), controlPoint2: NSMakePoint(101.74, 58.97))
        bezier6Path.curveToPoint(NSMakePoint(93.25, 60.07), controlPoint1: NSMakePoint(97.36, 59.04), controlPoint2: NSMakePoint(95.23, 59.27))
        bezier6Path.curveToPoint(NSMakePoint(90.68, 62.52), controlPoint1: NSMakePoint(92.18, 60.5), controlPoint2: NSMakePoint(90.78, 61.21))
        bezier6Path.curveToPoint(NSMakePoint(88.71, 60.34), controlPoint1: NSMakePoint(90.6, 61.44), controlPoint2: NSMakePoint(89.6, 60.78))
        bezier6Path.curveToPoint(NSMakePoint(82.11, 58.92), controlPoint1: NSMakePoint(86.67, 59.34), controlPoint2: NSMakePoint(84.35, 59.07))
        bezier6Path.curveToPoint(NSMakePoint(76.11, 60.07), controlPoint1: NSMakePoint(80.07, 59.05), controlPoint2: NSMakePoint(78.02, 59.3))
        bezier6Path.curveToPoint(NSMakePoint(73.54, 62.52), controlPoint1: NSMakePoint(75.05, 60.5), controlPoint2: NSMakePoint(73.64, 61.21))
        bezier6Path.curveToPoint(NSMakePoint(72.11, 60.63), controlPoint1: NSMakePoint(73.48, 61.65), controlPoint2: NSMakePoint(72.81, 61.06))
        bezier6Path.curveToPoint(NSMakePoint(65.32, 58.94), controlPoint1: NSMakePoint(70.09, 59.41), controlPoint2: NSMakePoint(67.62, 59.14))
        bezier6Path.curveToPoint(NSMakePoint(59.67, 60.07), controlPoint1: NSMakePoint(63.4, 59.07), controlPoint2: NSMakePoint(61.46, 59.35))
        bezier6Path.curveToPoint(NSMakePoint(57.1, 62.52), controlPoint1: NSMakePoint(58.6, 60.5), controlPoint2: NSMakePoint(57.2, 61.21))
        bezier6Path.curveToPoint(NSMakePoint(55.67, 60.63), controlPoint1: NSMakePoint(57.04, 61.65), controlPoint2: NSMakePoint(56.37, 61.06))
        bezier6Path.curveToPoint(NSMakePoint(49.09, 58.96), controlPoint1: NSMakePoint(53.71, 59.45), controlPoint2: NSMakePoint(51.32, 59.16))
        bezier6Path.curveToPoint(NSMakePoint(43.66, 60.07), controlPoint1: NSMakePoint(47.25, 59.08), controlPoint2: NSMakePoint(45.38, 59.38))
        bezier6Path.curveToPoint(NSMakePoint(41.09, 62.52), controlPoint1: NSMakePoint(42.59, 60.5), controlPoint2: NSMakePoint(41.18, 61.21))
        bezier6Path.curveToPoint(NSMakePoint(39.12, 60.34), controlPoint1: NSMakePoint(41.01, 61.44), controlPoint2: NSMakePoint(40, 60.78))
        bezier6Path.curveToPoint(NSMakePoint(32.54, 58.92), controlPoint1: NSMakePoint(37.09, 59.34), controlPoint2: NSMakePoint(34.77, 59.07))
        bezier6Path.curveToPoint(NSMakePoint(26.56, 60.07), controlPoint1: NSMakePoint(30.51, 59.06), controlPoint2: NSMakePoint(28.47, 59.3))
        bezier6Path.curveToPoint(NSMakePoint(23.99, 62.52), controlPoint1: NSMakePoint(25.5, 60.5), controlPoint2: NSMakePoint(24.09, 61.21))
        bezier6Path.curveToPoint(NSMakePoint(22.56, 60.63), controlPoint1: NSMakePoint(23.93, 61.65), controlPoint2: NSMakePoint(23.27, 61.06))
        bezier6Path.curveToPoint(NSMakePoint(16.08, 58.96), controlPoint1: NSMakePoint(20.63, 59.46), controlPoint2: NSMakePoint(18.27, 59.17))
        bezier6Path.curveToPoint(NSMakePoint(11.7, 59.71), controlPoint1: NSMakePoint(14.6, 59.1), controlPoint2: NSMakePoint(13.12, 59.26))
        bezier6Path.curveToPoint(NSMakePoint(9.53, 60.63), controlPoint1: NSMakePoint(10.86, 59.97), controlPoint2: NSMakePoint(10.27, 60.21))
        bezier6Path.curveToPoint(NSMakePoint(8.22, 61.97), controlPoint1: NSMakePoint(9.01, 60.94), controlPoint2: NSMakePoint(8.45, 61.39))
        bezier6Path.curveToPoint(NSMakePoint(8.1, 62.52), controlPoint1: NSMakePoint(8.11, 62.22), controlPoint2: NSMakePoint(8.12, 62.29))
        bezier6Path.lineToPoint(NSMakePoint(8.09, 62.33))
        bezier6Path.curveToPoint(NSMakePoint(7.99, 61.97), controlPoint1: NSMakePoint(8.05, 62.21), controlPoint2: NSMakePoint(8.04, 62.08))
        bezier6Path.curveToPoint(NSMakePoint(5.84, 60.21), controlPoint1: NSMakePoint(7.64, 61.13), controlPoint2: NSMakePoint(6.62, 60.54))
        bezier6Path.curveToPoint(NSMakePoint(5.15, 59.93), controlPoint1: NSMakePoint(5.61, 60.11), controlPoint2: NSMakePoint(5.38, 60.01))
        bezier6Path.curveToPoint(NSMakePoint(3.72, 59.5), controlPoint1: NSMakePoint(4.68, 59.78), controlPoint2: NSMakePoint(4.2, 59.62))
        bezier6Path.curveToPoint(NSMakePoint(2.85, 59.3), controlPoint1: NSMakePoint(3.43, 59.43), controlPoint2: NSMakePoint(3.14, 59.35))
        bezier6Path.curveToPoint(NSMakePoint(0.92, 59.03), controlPoint1: NSMakePoint(2.21, 59.18), controlPoint2: NSMakePoint(1.56, 59.09))
        bezier6Path.curveToPoint(NSMakePoint(10.07, 86.23), controlPoint1: NSMakePoint(2.24, 68.54), controlPoint2: NSMakePoint(5.42, 77.83))
        bezier6Path.lineToPoint(NSMakePoint(13.46, 92.31))
        bezier6Path.curveToPoint(NSMakePoint(80.41, 160.26), controlPoint1: NSMakePoint(31.32, 118.99), controlPoint2: NSMakePoint(55.37, 140.59))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.lineToPoint(NSMakePoint(80.41, 160.26))
        bezier6Path.closePath()
        bezier6Path.miterLimit = 4
        GlukloaderYosemite.color0.setFill()
        bezier6Path.fill()



        NSGraphicsContext.restoreGraphicsState()
    }

    //// Generated Images

    public class var imageOfGlukitIcon: NSImage {
        if Cache.imageOfGlukitIcon != nil {
            return Cache.imageOfGlukitIcon!
        }

        Cache.imageOfGlukitIcon = NSImage(size: NSMakeSize(16, 16), flipped: false) { (NSRect) -> Bool in 
                GlukloaderYosemite.drawGlukitIcon()

            return true
        }

        return Cache.imageOfGlukitIcon!
    }

}
